path_tlc: "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_"

date_start: "2023-01"

date_end: "2023-04"

date_valid_str: "2023-03"

date_test_str: "2023-04"

col_date_hour: "tpep_pickup_datetime"

link_shape: 'https://d37ci6vzurychx.cloudfront.net/misc/taxi_zones.zip'

path_to_save_shape: 'data/01_raw/'

params_hgbr: {
  "loss": 'squared_error',
  "learning_rate": 0.05,
  "max_iter": 1000,
  "max_depth": 7,
  "categorical_features": ["VendorID", "RatecodeID", "store_and_fwd_flag", "PULocationID", "DOLocationID", "payment_type"],
  "random_state": 12,
}

path_shape_locations: 'data/01_raw/taxi_zones/taxi_zones.shp'